### ISSUE TITLE
ImportError: cannot import name 'day_start_end' from 'homeassistant.components.recorder.statistics'

### ISSUE THREAD

**Issue by codyc1515** [codyc1515/hacs_contact_energy#4]
This error originated from a custom integration.

Logger: homeassistant.config
Source: custom_components/contact_energy/sensor.py:17
Integration: contact_energy (documentation, issues)
First occurred: 9:31:58 AM (1 occurrences)
Last logged: 9:31:58 AM

Platform error: sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config.py", line 928, in async_process_component_config
    platform = p_integration.get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 779, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 796, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/contact_energy/sensor.py", line 17, in <module>
    from homeassistant.components.recorder.statistics import (
ImportError: cannot import name 'day_start_end' from 'homeassistant.components.recorder.statistics' (/usr/src/homeassistant/homeassistant/components/recorder/statistics.py)

Appears to be related to HA Core change: https://github.com/home-assistant/core/pull/87321

**Comment by codyc1515** [comment]
Fixed by https://github.com/codyc1515/hacs_contact_energy/commit/256e14c6636d6f36395aa0b4647c938e606e7fa7
